import Head from 'next/head'
import { Inter } from 'next/font/google'
import { signOut, useSession } from 'next-auth/react'
import Link from 'next/link'
import { CustomNextPage } from '@/types/CustomNextPage'

const inter = Inter({ subsets: ['latin'] })

const Home: CustomNextPage = () => {
  const { data, status } = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data?.user?.name || <Link href="/auth/signin">SIGNIN</Link>}
        {status === 'authenticated' && (
          <button onClick={() => signOut()}>SIGN OUT</button>
        )}
        <Link style={{ marginLeft: '1rem' }} href="categories">
          PROTECTED PAGE
        </Link>
      </main>
    </>
  )
}

export default Home
